sudo: required
language: python
python:
  - "3.7"

before_install:
  - |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|^(LICENSE)'
    then
      echo "Not running CI since only docs were changed."
      exit
    fi
  - sudo apt-get install -y chrpath
addons:
  apt:
    update: true


script:
  - cd ${TRAVIS_BUILD_DIR}
  - pip3 install -r requirements.txt
  - pip3 install nuitka
  - cd ${TRAVIS_BUILD_DIR}/xiaomi_flashable_firmware_creator/
  - python3 -m nuitka --follow-imports create_flashable_firmware.py --standalone
  - python3 -m nuitka --follow-imports main.py --standalone --plugin-enable=qt-plugins
  - zip -r9 -r -j -q xiaomi_flashable_firmware_creator-cli.zip create_flashable_firmware.dist/*
  - cp -r data/ helpers/ i18n/ icon.png main.dist/*
  - zip -r9 -r -q xiaomi_flashable_firmware_creator-gui.zip main.dist/*

deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GIT_OAUTH_TOKEN"
  file_glob: true
  file: ${TRAVIS_BUILD_DIR}/xiaomi_flashable_firmware_creator/*.zip
  on:
    tags: false
    repo: XiaomiFirmwareUpdater/xiaomi-flashable-firmware-creator.py
    branch: gui

notifications:
  email:
    on_success: never
    on_failure: always

branches:
  except:
    - /^(?i:untagged)-.*$/
